# Site settings
title: Ritvik Kapila
description: Building something new
author: Ritvik Kapila
email: ritvik.iitd@gmail.com
url: https://ritvik-kapila.github.io
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/
  news:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Include
include:
  - _redirects

# SEO
seo:
  type: Person
  name: Ritvik Kapila
  job_title: Building something new
  organization: Stealth Startup
  url: https://ritvik-kapila.github.io
  image: /assets/images/RitvikKapila.png
  social:
    google_scholar: https://scholar.google.com/citations?user=vTYNQkwAAAAJ
    linkedin: https://linkedin.com/in/ritvik-kapila
    github: https://github.com/RitvikKapila
    twitter: https://twitter.com/RitvikKapila
